@baseUrl = http://localhost:3333
#@auth_token = {{authenticate.response.body.access_token}}

# @name create_sector
POST {{baseUrl}}/admin/sector
Content-Type: application/json

{
  "name": "Teste 4",
  "description": "Setor criado para fins de teste"
}
###


# @name create_machine
POST {{baseUrl}}/admin/machine
Content-Type: application/json

{
  "name": "Test Machine",
  "description": "Máquina criado para fins de teste",
  "sectorId": "480005be-b0db-4d6a-b85f-b122bf967571"
}
###

# @name create_machine_operator
POST {{baseUrl}}/admin/machine-operator
Content-Type: application/json

{
  "name": "Test Operator",
  "number": 1,
  "sectorId": "480005be-b0db-4d6a-b85f-b122bf967571"
}
###



